/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package textgame;

import java.awt.Color;
import java.awt.Graphics;
import textgame.map.Map;

/**
 *
 * @author patrick
 */
public class MapPane extends javax.swing.JPanel {

    private Map map = new Map();
    
    public MapPane() {
        initComponents();
        this.map = map;
    }
    
    @Override
    public void paint(Graphics g) {
        map.drawMap(g);
        g.setColor(Color.white);
        g.drawString("TEST MAP ONLY", 10, 180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(280, 196));
        setMinimumSize(new java.awt.Dimension(280, 196));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(280, 196));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
