/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package textgame;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author patrick
 */
public class MapPane extends javax.swing.JPanel {

    /**
     * Creates new form testPane
     */
    public MapPane() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        drawMap(g);
        g.setColor(Color.white);
        g.drawString("TEST MAP ONLY", 10, 180);
    }
    
    public void drawMap(Graphics g) {
        Image i = null;
        try {
            URI imageurl = getClass().getResource("grid.png").toURI();
            File f = new File(imageurl);
            i = ImageIO.read(f);
            System.out.println("Success");
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MapPane.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.drawImage(i, 0, 0, null);
        g.setColor(Color.red);
        g.setFont(new Font("Tahoma", Font.BOLD, 20));
        g.fillRect(16, 1, 10, 9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(280, 196));
        setMinimumSize(new java.awt.Dimension(280, 196));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(280, 196));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
